### ISSUE TITLE
Versturen 

### ISSUE THREAD

**Issue by Finnapeachey** [Peachey-Schoorl/schooltrui-vsz#9]
Maken dat je als optie kan kiezen bij het betalen om hem thuis te laten bezorgen, (met extra kosten) en dat je dan je adres en alles kan invullen. Als je voor bezorgen kiest

**Comment by Potherca** [comment]
We moeten even kijken hoe Stripe dit doet. Het kan zijn dit betekend dat er nog een prijs moet worden gemaakt voor het product.

**Comment by Potherca** [comment]
Stripe heeft opties voor "Verzenden" maar dat kan alleen met "fixed price" (Dus de gebruiker kan niet meer betalen als ze dat zouden willen).

**Comment by Potherca** [comment]
Voorbeeld: [https://buy.stripe.com/6oEcPK9B5eN80NieUY](https://buy.stripe.com/6oEcPK9B5eN80NieUY?locale=nl)

**Comment by Potherca** [comment]
Resolved with d9ca1c4d476b697b5147b81766a313e8c9d60c35
